[project]
name = "pas-alpha-prototype-be"
version = "0.1.0"
description = "Prior Approval System - Alpha Prototype"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databases[aiosqlite]>=0.9.0",
    "fastapi>=0.115.12",
    "pydantic>=2.11.5",
    "uvicorn>=0.34.3",
]
